<img src=https://desafiolatam.com/assets/home/logo-academia-bla-790873cdf66b0e681dfbe640ace8a602f5330bec301c409744c358330e823ae3.png>

### Nombre Alumno: Ramiro Silva
### Generación: G48
###  Profesoras: 
### Fecha : 08-08-2022

# Desafío - Regresión desde el aprendizaje de máquinas

   * Para poder realizar este desafío debes haber revisado la lectura y videos correspondiente a la unidad.
   * Crea una carpeta de trabajo y guarda todos los archivos correspondientes (notebook y csv).
   * Una vez terminado el desafío, comprime la carpeta y sube el .zip

# Contexto sobre la base de datos

##### En esta sesión trabajaremos una base de datos sobre los precios de las viviendas en Boston, utilizada en el paper Harrison Jr, D., & Rubinfeld, D. L. (1978). Hedonic housing prices and the demand for clean air. Journal of environmental economics and management, 5(1), 81-102.
##### Nuestro objetivo es desarrollar un modelo predictivo para el valor mediano de las casas mediante el entrenamiento de un modelo de regresión lineal.

* crim : Tasa de criminalidad por sector de Boston
* zn proporción de terreno residencial asignado para terrenos baldíos.
* indus proporción de negocios no asociados al comercio por sector.
* chas Dummy. 1 si el sector colinda con el río Charles, 0 de lo contrario.
* nox Concentración de dióxido de carbono
* rm cantidad promedio de habitaciones por casa.
* age proporción de casas construídas antes de 1940
* dis distancia promedio a cinco centros de empleos.
* rad índice de accesibilidad a autopistas.
* tax nivel de impuestos asociados a viviendas.
* ptratio razón alumno:profesor por sector de Boston.
* black proporción de afroamericanos por sector de Boston.
* lstat porcentaje de población de estratos bajos.
* medv valor mediano de las casas

## Desafío 1: Prepare el ambiente de trabajo

##### * Importe las librerías básicas para el análisis de datos.
##### * Importe el módulo linear_model , y las funciones mean_squared_error , r2_score y train_test_split .
##### * Importe la base de datos boston.csv y elimine la columna Unnamed: 0 .
##### * Obtenga las medidas descriptivas de la base de datos con .describe() .

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import warnings
warnings.filterwarnings(action='ignore')
#from sklearn.preprocessing import PolynomialFeatures as polynom
from sklearn.linear_model import LinearRegression as linreg
#from sklearn.pipeline import make_pipeline
plt.style.use('seaborn-whitegrid')
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
#importamos todas las librerías necesarias para trabajar.

In [24]:
df = pd.read_csv('boston.csv') #con pd.read_csv leemos el archivo a trabaja.

In [25]:
df.drop(columns= 'Unnamed: 0',axis = 1,inplace= True)# eliminamos la columna Unnamed

In [26]:
df.shape #con .shape podemos ver como esta conformado nuestro df, en este caso son 506 registros y 14 columnas

(506, 14)

In [27]:
df.head() #visualizamos el df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [28]:
df.dtypes 

crim       float64
zn         float64
indus      float64
chas         int64
nox        float64
rm         float64
age        float64
dis        float64
rad          int64
tax          int64
ptratio    float64
black      float64
lstat      float64
medv       float64
dtype: object

In [29]:
df.describe()

crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio       black  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat        medv  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

## Desafío 2: División de la muestra
##### * Genere conjuntos de entrenamiento y validación con train_test_split .
##### * Genere segmentaciones del 33% para las muestras de validación.
##### * Incluya una semilla pseudoaleatoria

In [30]:
y_vec= df.loc[:, 'medv'] # detectamos nuestra vector objetivo, que en este caso es medv 
X_mat = df.loc[:, 'crim':'lstat'] # detectamos nuestra matriz de atributos.
# se separan los 2 conjuntos a trabajar

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X_mat, y_vec, test_size=.33, random_state=11238)

# dividimos la muestra en 2 partes entrenamiento y validación con segmentaciones del 33% para las muestras de validación

In [32]:
X_train.shape #con .shape verificamos que se hayan seleccionado el 67% de los registros

(339, 13)

In [33]:
X_test.shape #con .shape verificamos que se hayan seleccionado el 33% de los registros

(167, 13)

In [34]:
y_train.shape

(339,)

In [35]:
y_test.shape

(167,)

In [36]:
y_test.head()

191    30.5
164    22.7
132    23.0
61     16.0
120    22.0
Name: medv, dtype: float64

In [37]:
X_test.head() #Verificamos que los datos coincidan

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
191  0.06911  45.0   3.44     0  0.437  6.739  30.8  6.4798    5  398   
164  2.24236   0.0  19.58     0  0.605  5.854  91.8  2.4220    5  403   
132  0.59005   0.0  21.89     0  0.624  6.372  97.9  2.3274    4  437   
61   0.17171  25.0   5.13     0  0.453  5.966  93.4  6.8185    8  284   
120  0.06899   0.0  25.65     0  0.581  5.870  69.7  2.2577    2  188   

     ptratio   black  lstat  
191     15.2  389.71   4.69  
164     14.7  395.11  11.64  
132     21.2  385.76  11.12  
61      19.7  378.08  14.44  
120     19.1  389.15  14.37

### Comentarios:

In [64]:
#Un comentario al respecto de la semila pseudo-aleatoria, lo que realiza es tomar filas al azar pero elegir siempre las mismas
#debido que si usamos random cada vez que ejecutemos va elegir filas al azar

## Desafío 3: Generación de modelos

##### * Ahora implementaremos dos versiones del modelo lineal:
#####   * Con intercepto y atributos normalizados.
#####   * Sin intercepto y atributos no normalizados.
##### * Cada versión debe generarse en un nuevo objeto inicializado.
##### Posteriormente se deben entrenar los modelos especificando la matriz y vector de entrenamiento.
##### Con los modelos entrenados, genere una predicción de matriz de validación.

In [39]:
modelo_normalizado = linear_model.LinearRegression(fit_intercept=True, normalize=True).fit(X_train, y_train) 
modelo_normalizado
#implementamos la versión del modelo normalizado, con  intercepto y atributos normalizados 

LinearRegression(normalize=True)

In [40]:
modelo_no_normalizado = linear_model.LinearRegression(fit_intercept=False, normalize=False).fit(X_train, y_train)# inicializando objeto 
modelo_no_normalizado
#implementamos la versión del modelo NO normalizado, sin  intercepto y atributos NO normalizados

LinearRegression(fit_intercept=False)

In [41]:
modelo_normalizado.coef_ # Obtenemos los coeficientes estimados mediante el ajuste del modelo normalizado.

array([-7.30501824e-02,  2.66902156e-02,  4.73626638e-02,  2.41132251e+00,
       -1.33619576e+01,  4.79795832e+00, -2.32271350e-02, -1.28935869e+00,
        2.48826365e-01, -1.30239881e-02, -1.05160097e+00,  8.67216006e-03,
       -4.34084392e-01])

In [42]:
modelo_no_normalizado.coef_ # Obtenemos los coeficientes estimados mediante el ajuste del modelo NO normalizado.

array([-0.06138418,  0.02896326,  0.01624546,  2.87298217, -0.3233765 ,
        6.44198445, -0.02719666, -0.84036275,  0.13866055, -0.01049006,
       -0.57389555,  0.01342821, -0.3482554 ])

In [43]:
modelo_normalizado.intercept_  #para el caso del modelo normalizado, vemos que el valor del intercepto es de 42.004

30.32854407894918

In [44]:
modelo_no_normalizado.intercept_  #para el caso del modelo NO normalizado, vemos que el valor del intercepto es 0, ya que ni se considera el intercepto

0.0

In [45]:
modelo_normalizado_yhat = modelo_normalizado.predict(X_test) # se genera una predicción de matriz de validación, con el modelo_normalizado
modelo_normalizado_yhat[:5]

array([30.53158784, 24.75093137, 19.81038463, 17.42282328, 22.50970106])

In [46]:
modelo_no_normalizado_yhat = modelo_no_normalizado.predict(X_test) # se genera una predicción de matriz de validación, con el modelo_no_normalizado
modelo_no_normalizado_yhat[:5]

array([29.73800187, 22.44563267, 21.65888321, 17.68558194, 21.81107521])

## Desafío 4: Obtención de métricas

##### * Ahora generemos una función llamada report_scores que ingrese como argumentos el vector de datos predichos y el vector de datos por validar.
##### * La función debe imprimir las métricas del Error Cuadrático Promedio y R2.
##### *  Reporte las métricas para ambos modelos. En base a ello, seleccione el mejor modelo.

In [47]:
def report_scores(model, y_test):
    print("Error Cuadrático Promedio: {0}".format(mean_squared_error(y_test, model, squared=True).round(1)))
    print("R2: {0}".format( r2_score(y_test, model).round(1)))

In [48]:
report_scores(modelo_normalizado_yhat, y_test)

Error Cuadrático Promedio: 30.7
R2: 0.6


In [49]:
report_scores(modelo_no_normalizado_yhat, y_test)

Error Cuadrático Promedio: 34.3
R2: 0.6


## Comentarios

* __Comparando los 2 modelos normalizado y no_normalizado, podemos ver que el modelo normalizado es el mejor modelo, ya que su error cuadratico medio es menor en comparacion al no normalizado.__ 

## Desafío 5: Refactorización del modelo

##### * Genere una función llamada fetch_features que ingrese como argumentos la base de datos y el nombre del vector objetivo. 
##### * El nombre del vector debe ser medv por defecto
##### * La función debe retornar una lista con las correlaciones entre cada atributo y el vector objetivo y su nombre.
##### * Reporte brevemente cuales los 6 atributos con una mayor correlación con medv.

In [50]:
def fetch_features(DataFrame, vector_objetivo= 'medv'): #funcion recibe un df y el vector objetivo que por defecto es medv
    correlado = abs(df.corr()[vector_objetivo]) #se define correlado como la correlación entre mi df y el vector objetivo, al poner abs se traen los valores absolutos
    return correlado.sort_values(ascending= False) #return, retorna el correlado, al agregar .sort_values(ascending = False), lo ordena de mayor a menor
    


In [51]:
 fetch_features(df, vector_objetivo= 'medv')


medv       1.000000
lstat      0.737663
rm         0.695360
ptratio    0.507787
indus      0.483725
tax        0.468536
nox        0.427321
crim       0.388305
rad        0.381626
age        0.376955
zn         0.360445
black      0.333461
dis        0.249929
chas       0.175260
Name: medv, dtype: float64

los 6 atributos con una mayor correlación son:

lstat    
rm        
ptratio   
indus     
tax     
nox       

Se descarta medv ya que se estaria viendo la correlación entre dos variables que son lo mismo.

## Desafío 6: Refactorización del modelo predictivo

##### * Genere otros conjuntos de entrenamiento y validación en base a una matriz con los 6 atributos
##### * identificados y el vector objetivo.
##### * Entrene un modelo en base al mejor desempeño.
##### * Reporte las métricas para el nuevo modelo.

In [52]:
df6 = df[['medv', 'lstat','rm', 'ptratio', 'indus', 'tax', 'nox']]

y_vec= df6.loc[:, 'medv'] # detectamos nuestra vector objetivo, que en este caso es medv 
X_mat = df6.loc[:, ['lstat','rm', 'ptratio', 'indus', 'tax', 'nox']] # detectamos nuestra matriz de atributos.
 
# se separan los 2 conjuntos a trabajar

In [53]:
X_train6, X_test6, y_train6, y_test6 = train_test_split(X_mat, y_vec, test_size=.33, random_state=11238)

In [54]:
modelo_normalizado6 = linear_model.LinearRegression(fit_intercept=True, normalize=True).fit(X_train6, y_train6) 

In [55]:
modelo_normalizado6.coef_ # Obtenemos los coeficientes estimados mediante el ajuste del modelo normalizado.

array([-0.46594479,  5.3101511 , -0.94903905,  0.07504978, -0.00546771,
       -3.39026222])

In [56]:
modelo_normalizado6.intercept_  #para el caso del modelo normalizado, vemos que el valor del intercepto es de 42.004

15.940503964151137

In [57]:
modelo_normalizado_yhat6 = modelo_normalizado6.predict(X_test6) # se genera una predicción de matriz de validación, con el modelo_normalizado
modelo_normalizado_yhat6[:5]

array([31.7154155 , 24.86653591, 21.61377952, 19.49294024, 21.2161735 ])

In [58]:
report_scores(modelo_normalizado_yhat6, y_test6)

Error Cuadrático Promedio: 37.5
R2: 0.5


# Comentarios:

¿Cómo es el desempeño del modelo refactorizado respecto a los 2 modelos anteriores?

In [59]:
#El desempeño del modelo es peor esto debido que si bien se utilizaron las 6 mejores variables que tenian mayor correlacion
#con la variable dependiente, pero cabe destacar que se dejaron afuera otras variables que tambien eran buenas por asi decirlo.

##  Desafío 7: Predicción de casos

##### *  A continuación se generaron dos arrays que representan el peor escenario posible ( worst_neighbor ) y el mejor escenario posible ( best_neighbor ).

*  worst_neighbor = np.array([37.9, 3.5, 12.6, 27.7, 187, 0.87]).reshape(1, -1)


*  best_neighbor = np.array([1.73, 8.7, 22, 0.46, 711, 0.38]).reshape(1, -1)

##### *  Ingrese los arrays en el modelo entrenado y reporte cuál sería el valor esperado dada las condiciones.

In [60]:
best_neighbor = np.array([1.73, 8.7, 22, 0.46, 711, 0.38]).reshape(1, -1)
worst_neighbor = np.array([37.9, 3.5, 12.6, 27.7, 187, 0.87]).reshape(1, -1)

In [61]:
best_neighbor

array([[1.73e+00, 8.70e+00, 2.20e+01, 4.60e-01, 7.11e+02, 3.80e-01]])

In [62]:
modelo_normalizado_yhat6 = modelo_normalizado6.predict(best_neighbor) # se genera una predicción de matriz de validación, con el modelo_normalizado
modelo_normalizado_yhat6
    

array([35.31255605])

In [63]:
modelo_normalizado_yhat6 = modelo_normalizado6.predict(worst_neighbor) # se genera una predicción de matriz de validación, con el modelo_normalizado
modelo_normalizado_yhat6

array([3.01572229])

In [ ]:
#Segun el modelo entrenado el valor mediano de las casas (MEDV) sería para best_neighbor = 35.31255605 
#y worst_neighbor = 3.01572229